### ISSUE TITLE
Getting unauthorized when I call jobs/{jobId}/submit

### ISSUE THREAD

**Issue by JimmyHeartbreaker** [Azure/hpcpack-rest-api-spec#13]
Hi,

I hope someone can help me on this issue, it seems quite trivial.
We have been using Microsoft HPC for quite sometime via the provided Microsoft.HPC.SDK but we no longer wish to rely on this package because it relies on .Net Framework. I discovered this repository as a source of the API Documentation.

I am stuck trying to submit a job
I have sent the following actions:
**https://`<headnode>`/hpc/jobs : jobId**  <- OK

followed by
**https://`<headnode>`/hpc/jobs/`{jobId}`/submit** <- Unauthorized

the submit action fails with Unauthoirzed:401 and no additional information.
The user is an Administrator in HPC (also a JobAdministrator and a User) and I pass the same username/password in both of the above actions. Various other actions work fine and I can submit jobs through the 2019 HPC Cluster Manager as the same user.

Under what conditions would submit give Unauthorized? Am I doing something wrong?

Kind regards
James

**Comment by YutongSun** [comment]
@JimmyHeartbreaker , we are working on a new release of Microsoft.HPC.SDK on .Net 6/8 and .NetStandard 2.0. Could you let us know your scenarios and requirements for the .Net SDK while we are checking the REST API for you?

**Comment by YutongSun** [comment]
@JimmyHeartbreaker , we are working on a new release of Microsoft.HPC.SDK on .Net 6/8 and .NetStandard 2.0. Could you let us know your scenarios and requirements for the .Net SDK while we are checking the REST API for you?

**Comment by coin8086** [comment]
Hi @JimmyHeartbreaker, when creating/submitting a job, you need to add the job property "username" by who the job will run, as stated by https://learn.microsoft.com/en-us/previous-versions/windows/desktop/hh529668(v=vs.85) and https://learn.microsoft.com/en-us/previous-versions/windows/desktop/hh560265(v=vs.85). You need also to provide the job property "password" for the "username" if the user's credential is not cached in server. Please note that this "username" can be different from the user of the HTTP authentication, and even they're the same user you should still specify the "username" property of the job. FYI.

**Comment by JimmyHeartbreaker** [comment]
> Hi @JimmyHeartbreaker, when creating/submitting a job, you need to add the job property "username" by who the job will run, as stated by https://learn.microsoft.com/en-us/previous-versions/windows/desktop/hh529668(v=vs.85) and https://learn.microsoft.com/en-us/previous-versions/windows/desktop/hh560265(v=vs.85). You need also to provide the job property "password" for the "username" if the user's credential is not cached in server. Please note that this "username" can be different from the user of the HTTP authentication, and even they're the same user you should still specify the "username" property of the job. FYI.

Thank you, I can now submit the jobs.

@YutongSun our scenario is like this - https://learn.microsoft.com/en-us/powershell/high-performance-computing/soa-tutorial-write-your-first-soa-service-and-client?view=hpc19-ps
except we are using System.ServiceModel.ChannelFactory<TService>.CreateChannel(Session.EndpointReference) to create a channel. We are currently discussing alternatives to RPC style communication.

Do you know when we can expect a .Net Standard or .Net6/8 compatible client package?
